config/routes.rb
Omrails::Application.routes.draw do
  resources :pins

  devise_for :users
  get 'about' => 'pages#about'
  root :to => 'pages#home'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description

  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable, 
         :rememberable, :trackable, :validatable
  # attr_accessible :title, :body
  attr_accessible :email, :password, :password_confirmation, :remember_me, :provider, :uid, :name, :as => [:default, :admin]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @pin = Pin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = Pin.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = Pin.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = Pin.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert-box alert">
      <h5 class="subheader" style="color:white;">#{messages}</h5>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
    <div class="footer">
      <small>
      <footer class="row">
        <div class="large-12 columns"><hr />
          <div class="row">

            <div class="large-6 columns">
              <p>&copy; One Month Rails application by <%= link_to "Alex Bakus", "http://alexanderbakus.com", :target => "_blank" %></p>
            </div>

            <div class="large-6 columns">
              <ul class="inline-list right">
                <li><a href="#">Link 1</a></li>
                <li><a href="#">Link 2</a></li>
                <li><a href="#">Link 3</a></li>
                <li><a href="#">Link 4</a></li>
              </ul>
            </div>

          </div>
        </div>
      </footer>
      </small>
     </div> 

    <!-- End Footer -->

app/views/layouts/_header.html.erb
<!-- Navigation -->

  <div class="row">

    <div class="large-12 columns">
      <nav class="top-bar fixed containt-to-grid">
        <ul class="title-area">
          <!-- Title Area -->
          <li class="name">
            <h1>
          		<%= link_to "One Month Rails" , root_path %> 
            </h1>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
        </ul>
     
        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right">
            <li class="divider"></li>
            <li><%= link_to "About" , about_path %></li>
                <li class="divider"></li>
                <% if user_signed_in? %>
                  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
                  <li class="divider"></li>
                <% else %>
                  <li><%= link_to "Sign in", new_user_session_path %></li>
                  <li class="divider"></li>
                <% end %>
          </ul>
        </section>
      </nav>
      <!-- End Top Bar -->
    
  </div>
  </div>

<!-- End Navigation -->

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "One Month Rails" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="row">
    <div class="large-12 columns">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert-box success alert-#{name}") %>
      <% end %>
      <%= yield %>

      <%= render 'layouts/footer' %>
      
      <%= javascript_include_tag "application" %>
    </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="panel">
  <h1>About</h1>
  <p>
    One Month Rails is a project to teach 
    <%= link_to "Ruby on Rails", "http://rubyonrails.org" %>
    in one month. This is the sample application.
  </p>
</div

app/views/pages/home.html.erb
<div class="panel">
  <% if user_signed_in? %>
    <h1 class="subheader">Welcome to One Month Rails!</h1>
    <h4 class="subheader">I am excited you joined.</h4>
    <p>   
    <%= link_to "Edit Profile", edit_user_registration_path, class: "button large success" %>
    </p>
  <% else %>
    <h1>Welcome to One Month Rails!</h1>
    <h3 class="subheader">
    	You've found the home page for the 
    	<%= link_to "One Month Rails", "http://onemonthrails.com", :target => "_blank" %>
    	application.
    </h3>
    <p>
    	<%= link_to "Sing Up Now!" , new_user_registration_path, class: "button large success" %>
    </p>
  <% end %>
</div>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin) do |f| %>
  <%= f.error_notification %>

  <div class="row">
    <div class="large-6 columns">
      <%= f.input :description, as: :text, input_html: { rows: "3" } %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<tr>
  <td><%= pin.description %></td>
  <td><%= link_to 'Show', pin %></td>
  <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
  <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<h1 class="subheader">Listing pins</h1>

<div class="row">
  <table class="large-12 columns">
      <tr>
        <th><h4 class="subheader left">Description</h3></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    <%= render @pins %>
  </table>
</div>
<br />

<%= link_to 'New Pin', new_pin_path, class: "button" %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
  <div class="large-6 large-offset-3 columns">
    <div class="panel">
      
      <p>
        <%= @pin.description %>
      </p>
      <%= link_to 'Edit', edit_pin_path(@pin) %> |
      <%= link_to 'Back', pins_path %>
    </div>
  </div>
</div>

app/views/users/shared/_links.erb
<small><%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>
</small>